# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Code Canon
tagline:             'A lean, MEAN, Agile machine'
description:         'The personal page of programmer Dave Mun.'
url:                 http://davemun.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Dave Mun
  url:               http://github.com/davemun
  email:             mun.dave@gmail.com

# Custom vars
version:             1.0.0
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
